### ISSUE TITLE
Enchantments aren't working 

### ISSUE THREAD

**Issue by FoxChanHelpful** [Geolykt/NMSless-Zenchantments#19]
On every enchantment book there is an unbreaking 0 enchant. and when i apply enchantment to the item, it just turns into unbreaking one

**Comment by Geolykt** [comment]
NMS-less zenchantments is no longer supported, consider using [EnchantmentsPlus](https://github.com/Geolykt/EnchantmentsPlus) instead, which has full support and likely has this bug already fixed (with the side effect that anvils do not work in spigot - but you should be using paper anyways). It also has a Java 11 dependency for versions 3.x.x and newer, so if you are using Java 8, you can still use the 2.x.x LTS (although "LTS" is rather overselling it as I am only supporting it for another 6 months) releases. Reason for this change is that it became clear at that time that it might not be possible to maintain parity as well as the project inflating to too big of a size, which is why it was replaced by EnchantmentsPlus
